// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "JoystickServo.h"
JoystickServo::JoystickServo() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::blackServo);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	servoPossition = 0.5;	// Center Servo
}
// Called just before this Command runs the first time
void JoystickServo::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void JoystickServo::Execute() {
	servoPossition = ((Robot::oi->getDriverJoystick()->GetRawAxis(0)) + 1.0)/2.0;
	Robot::blackServo->setPossition(servoPossition);
	
}
// Make this return true when this Command no longer needs to run execute()
bool JoystickServo::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void JoystickServo::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void JoystickServo::Interrupted() {
}
